

const APP_ACTIONS = {
  SET_LOADING: 'SET_LOADING',
  SET_USER: 'SET_USER',
  SET_TASKS: 'SET_TASKS',
  UPDATE_TASK: 'UPDATE_TASK',
  DELETE_TASK: 'DELETE_TASK',
  CREATE_TASK: 'CREATE_TASK',
};

export default APP_ACTIONS;